language: cpp

env:
  global:
  # AWS ID
  - secure: KJXyKEaAVk37l7VWZb2o2auBySTW5EZ1oDVoQ2HVIo0eqwrAGDmMLyl0fQEz9XDngDtrZJhmZ/USxaAAEejHUn8hzhIKlxBFZxvNMSWiQ+6pVV/N7+f+CX/bI558u+gIeC68N6nf41TSxq6s+6QZzWP3Eg4JjNSmRLm1Rpx1eTW+8GSh5ed/+BZ9RWjGfrldrzqD+7wKrk39VXoxDbUvBvJk+Q/eMHatD0DZr32+7sv+y2/wpzB+zjy1R1wZCu9Whshy5HaSTKiQ+hYC3xClLQ2zN6wl49mwkZaBKUG8q7/0N5Ke6ymlnEWCOwSd1YasQM2Qa83qJcrBkwRcyU6khvwYcEPN0JItoJhhUTsA1P26bpF2h5bnDIr6xlm5E8P/XUJ+nIFc0mux4vU/6461OE/Q3Md2nvc4Gjd9vlpTTq0F+YeYxn311hoPM4XtpC8gHyfH52CKWwDnUEFpMtUtTbzzo17fbutEYK0XC8s/8oUgs27uAF4WkVJV9rp4bDJBvhxOrPqEoaDCOgF83WBzgrm2kRP5t4Srs1VpbKFvYPli4MJvY2sO7cmAQM+CVH750sXo9a8FeUonCX0fF9+jb1sOyYadrslZahkZX7+eCfMUuqixuhNv9W0T/MKFI65poMotjeUoiXDBYTQEXokVpBKpPYoXwbrF+/P4bLfaiGY=
  # AWS Secret
  - secure: NqYRdJ4TvQGybDhHB6gI4KMvlqczbETOqT3JYt3nCuee5hLtcD9d6lr6AVXkMOuXf8asnpxCW6BUCqhOFyZOWErU8UnWTUYa/UJKvHTkKqaCOdTUYWaeNCGLZvbAgA30oAB8EU9pu/fsofht61gH91xnd+lZgNe8XPBQXl6ZxDc6vFaUNwt1DPLnKbbpD7vayfwKrrb9/EAiRTrMXdqYKGQTQFtWlBcSxQ5HqLueqWY7cu/jI9ItK/tEtXjwEJirhJrU3N8kuSU0/SWMd6yULE9WLIKrnyg+OB24SVsFNcoyehFecTuIcpdvHXOjKPtHnWuYfdaI2VeYYajOQZN1dBBYyNfBhUdZLCXRk5cj7UZ3eNhoiwdtGTrNzAzxSTueuzwRJkInu9WJPBKssWTA026QW5m4snlrYoSpmD0eeh0aFaNIa6AA+7PBVFjUsws/j22mw+5R0CBVfQLbdGCcOXmlV8pJ9EL81BvoMD0B0EMnNdERg2Z8dbCZBoBWUNzvFN5qH97I1QQPNZ7ccUJ8wKFtUyqCzvS/fZ/8IoC5TnFq99T13JLfRC7dm42X7TyxMmNeGvDzwLeOMPSPkUj5I/h+0assT5V1DZluciAjYXa2Qmo91JcgjYY4v8STOyhBgklvNML88NiMO2JFChGX5WSUCqdTc4ErOqilFAYGcb8=

matrix:
  include:
  - os: linux
    env: _linux_build
    dist: trusty
    sudo: required
    services:
    - docker
    before_install:
    - docker run -d --name xenial -v $(dirname $(pwd)):/root -v /home/travis/package:/package
      -e TRAVIS_BRANCH="$TRAVIS_BRANCH" -e TRAVIS_TAG="$TRAVIS_TAG" -w /root nimmis/ubuntu:16.04
    - docker exec -it xenial /root/obs-ndi/CI/install-dependencies-xenial.sh
    script:
    - docker exec -it xenial /root/obs-ndi/CI/build-xenial.sh
    after_success:
    - docker exec -it xenial /root/obs-ndi/CI/package-xenial.sh

deploy:
- provider: s3
  region: eu-central-1
  bucket: obs-ndi-linux-builds
  access_key_id: "$AWS_ID"
  secret_access_key: "$AWS_SECRET"
  local_dir: "/home/travis/package"
  skip_cleanup: true
  acl: public_read
  on:
    condition: "$TRAVIS_OS_NAME = linux"
    repo: Palakis/obs-ndi
    all_branches: true
