environment:
  CURL_VERSION: 7.39.0

install:
  - git submodule update --init --recursive
  - cd C:\projects\
  - if not exist dependencies2015.zip curl -kLO https://obsproject.com/downloads/dependencies2015.zip -f --retry 5 -C -
  - 7z x dependencies2015.zip -odependencies2015
  - set DepsPath32=%CD%\dependencies2015\win32
  - set DepsPath64=%CD%\dependencies2015\win64
  - call C:\projects\obs-ndi\CI\install-setup-qt.cmd
  - set build_config=Release
  - call C:\projects\obs-ndi\CI\install-build-obs.cmd
  - cd C:\projects\obs-ndi\
  - mkdir build32
  - mkdir build64
  - cd ./build32
  - cmake -G "Visual Studio 14 2015" -DW32_PTHREADS_LIB="C:\projects\obs-studio\build32\deps\w32-pthreads\%build_config%\w32-pthreads.lib" -Dw32-pthreads_DIR="C:\projects\obs-studio\build32\deps\w32-pthreads" -DQTDIR="%QTDIR32%" -DLibObs_DIR="C:\projects\obs-studio\build32\libobs" -DLIBOBS_INCLUDE_DIR="C:\projects\obs-studio\libobs" -DLIBOBS_LIB="C:\projects\obs-studio\build32\libobs\%build_config%\obs.lib" -DOBS_FRONTEND_LIB="C:\projects\obs-studio\build32\UI\obs-frontend-api\%build_config%\obs-frontend-api.lib" ..
  - cd ../build64
  - cmake -G "Visual Studio 14 2015 Win64" -DW32_PTHREADS_LIB="C:\projects\obs-studio\build64\deps\w32-pthreads\%build_config%\w32-pthreads.lib" -Dw32-pthreads_DIR="C:\projects\obs-studio\build64\deps\w32-pthreads" -DQTDIR="%QTDIR64%" -DLibObs_DIR="C:\projects\obs-studio\build64\libobs" -DLIBOBS_INCLUDE_DIR="C:\projects\obs-studio\libobs" -DLIBOBS_LIB="C:\projects\obs-studio\build64\libobs\%build_config%\obs.lib" -DOBS_FRONTEND_LIB="C:\projects\obs-studio\build64\UI\obs-frontend-api\%build_config%\obs-frontend-api.lib" ..

build_script:
  - call msbuild /m /p:Configuration=%build_config% C:\projects\obs-ndi\build32\obs-ndi.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - call msbuild /m /p:Configuration=%build_config% C:\projects\obs-ndi\build64\obs-ndi.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

before_deploy:
  - call C:\projects\obs-ndi\CI\prepare-slobs-package.cmd
  - 7z a "C:\projects\obs-ndi\build.zip" C:\projects\obs-ndi\release\*
  - 7z a "C:\projects\obs-ndi\build-slobs.zip" C:\projects\obs-ndi\release-slobs\*
  - set PATH=%PATH%;"C:\\Program Files (x86)\\Inno Setup 5"
  - iscc "C:\projects\obs-ndi\installer\installer.iss"

deploy_script:
  - ps: Push-AppveyorArtifact "C:\projects\obs-ndi\build.zip" -FileName "obs-ndi-$(git log --pretty=format:'%h' -n 1).zip"
  - ps: Push-AppveyorArtifact "C:\projects\obs-ndi\build-slobs.zip" -FileName "obs-ndi-$(git log --pretty=format:'%h' -n 1)-slobs.zip"
  - ps: Push-AppveyorArtifact "C:\projects\obs-ndi\installer\Output\obs-ndi-Windows-Installer.exe" -FileName "obs-ndi-$(git log --pretty=format:'%h' -n 1)-Windows-Installer.exe"

test: off

cache:
  - C:\projects\dependencies2015.zip
  - C:\projects\obs-studio-last-tag-built.txt
  - C:\projects\obs-studio